version: "3"

services:
  cloudvault-api:
    image: cloudvault-api
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - cloudvault-app
    depends_on:
      - mongo

  cloudvault-client:
    image: cloudvault-client
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - cloudvault-app
  mongo:
    image: mongo:5.0-bionic
    ports:
      - "27017:27017"
    networks:
      - cloudvault-app
    volumes:
      - mongo-data:/data/db

networks:
  cloudvault-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
