version: "3"

services:
  cloudvault-api:
    image: cloudvault-api
    build: ./server
    ports:
      - "2525:2525"
    networks:
      - cloudvault-app
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/cloudvault
      - /usr/src/cloudvault/node_modules

  cloudvault-client:
    image: cloudvault-client
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - cloudvault-app
    volumes:
      - ./client:/usr/src/cloudvault
      - /usr/src/cloudvault/node_modules

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - cloudvault-app
    volumes:
      - mongo-data:/data/db

networks:
  cloudvault-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
